
import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Source } from '../types';
import { ExternalLink, FileText, ShieldAlert, Quote, List, Hash, History, AlertTriangle, CheckCircle2 } from 'lucide-react';

interface ReportViewProps {
  markdown: string;
  sources: Source[];
  isGenerating: boolean;
}

const ReportView: React.FC<ReportViewProps> = ({ markdown, sources, isGenerating }) => {
  // Deduplicate sources by URI
  const uniqueSources: Source[] = Array.from(new Map(sources.map(s => [s.uri, s])).values());

  if (!markdown && !isGenerating) {
    return (
      <div className="h-full w-full bg-slate-50 flex flex-col items-center justify-center text-slate-400 p-8">
        <div className="w-24 h-24 bg-white rounded-full shadow-sm border border-slate-100 flex items-center justify-center mb-6">
          <FileText className="w-10 h-10 text-slate-300" />
        </div>
        <p className="text-xl font-light tracking-tight text-slate-600">Awaiting Intelligence Data</p>
        <p className="text-sm font-mono mt-2 text-slate-400">Select a target to begin analysis</p>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-slate-50 text-slate-900 font-sans relative">
      {/* Report Header */}
      <div className="px-8 py-5 border-b border-slate-200 bg-white shadow-sm flex items-center justify-between shrink-0 z-10">
        <div>
          <div className="flex items-center gap-2 text-rose-600 text-[10px] font-black uppercase tracking-[0.2em] mb-1">
            <ShieldAlert className="w-3 h-3" />
            Top Secret // Eyes Only
          </div>
          <h2 className="text-lg font-bold text-slate-800 tracking-tight">Intelligence Dossier</h2>
        </div>
        <div className="text-right hidden sm:block">
           <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-800 border border-slate-200">
            Generated by TruthSeeker Swarm
          </div>
        </div>
      </div>

      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-6 md:p-10 scroll-smooth">
        <div className="max-w-4xl mx-auto space-y-8">
          
          {/* Markdown Rendering with Custom Components */}
          <ReactMarkdown
            components={{
              // H1: Main Title
              h1: ({node, ...props}) => (
                <div className="mb-8 border-b-2 border-slate-900 pb-6">
                  <h1 className="text-4xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight" {...props} />
                </div>
              ),
              // H2: Section Headers
              h2: ({node, ...props}) => {
                // Auto-detect icon based on text content (simple heuristic)
                const text = props.children?.toString().toLowerCase() || '';
                let Icon = Hash;
                if (text.includes('situation') || text.includes('summary')) Icon = AlertTriangle;
                if (text.includes('evidence') || text.includes('findings')) Icon = List;
                if (text.includes('history') || text.includes('context')) Icon = History;

                return (
                  <div className="mt-10 mb-6 flex items-center gap-3">
                    <div className="p-2 bg-slate-900 text-white rounded-lg">
                      <Icon className="w-5 h-5" />
                    </div>
                    <h2 className="text-2xl font-bold text-slate-900 uppercase tracking-tight" {...props} />
                  </div>
                );
              },
              // H3: Subheaders
              h3: ({node, ...props}) => (
                <h3 className="text-lg font-bold text-cyan-700 mt-6 mb-3 flex items-center gap-2" {...props} />
              ),
              // Paragraphs
              p: ({node, ...props}) => (
                <p className="text-slate-600 leading-7 text-base mb-4 font-medium" {...props} />
              ),
              // Blockquote: Insight Card
              blockquote: ({node, children, ...props}) => (
                <div className="my-8 relative group">
                  <div className="absolute -inset-1 bg-gradient-to-r from-cyan-500 to-blue-600 rounded-xl opacity-20 blur group-hover:opacity-30 transition duration-200"></div>
                  <blockquote className="relative bg-white border-l-4 border-cyan-500 rounded-r-xl p-6 shadow-sm" {...props}>
                    <div className="absolute top-0 right-0 p-4 opacity-10">
                      <Quote className="w-8 h-8 text-cyan-900" />
                    </div>
                    <div className="text-lg text-slate-700 italic font-serif leading-relaxed">
                      {children}
                    </div>
                  </blockquote>
                </div>
              ),
              // Lists: Card Style
              ul: ({node, ...props}) => (
                <ul className="grid grid-cols-1 gap-2 my-6" {...props} />
              ),
              li: ({node, ...props}) => (
                <li className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm flex items-start gap-3 hover:border-cyan-300 transition-colors">
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
                  <span className="text-slate-700 leading-snug">{props.children}</span>
                </li>
              ),
              // Strong: Highlight
              strong: ({node, ...props}) => (
                <strong className="font-bold text-slate-900 bg-slate-100 px-1 rounded" {...props} />
              )
            }}
          >
            {markdown}
          </ReactMarkdown>
            
          {isGenerating && (
              <div className="mt-6 p-4 bg-slate-50 rounded-lg border border-slate-200 border-dashed flex items-center gap-3 animate-pulse">
                <div className="w-4 h-4 bg-cyan-500 rounded-full animate-bounce"></div>
                <span className="font-mono text-sm text-slate-500 uppercase">Incoming transmission...</span>
              </div>
          )}

          {/* Sources Footer */}
          {uniqueSources.length > 0 && (
            <div className="mt-12 pt-8 border-t border-slate-200">
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-6 flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500"></div>
                Verified Intelligence Sources ({uniqueSources.length})
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                {uniqueSources.map((source, idx) => (
                  <a 
                    key={idx} 
                    href={source.uri} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="flex flex-col justify-between p-3 h-20 rounded-lg border border-slate-200 bg-white hover:border-cyan-400 hover:shadow-md transition-all group relative overflow-hidden"
                  >
                    <div className="absolute top-0 right-0 w-16 h-16 bg-gradient-to-br from-slate-50 to-slate-100 rounded-bl-3xl -mr-4 -mt-4 z-0 group-hover:from-cyan-50 group-hover:to-cyan-100 transition-colors"></div>
                    
                    <div className="relative z-10 flex items-start justify-between">
                       <ExternalLink className="w-3.5 h-3.5 text-slate-400 group-hover:text-cyan-600 transition-colors" />
                    </div>
                    
                    <div className="relative z-10 overflow-hidden">
                      <div className="text-xs font-bold text-slate-700 truncate group-hover:text-cyan-900 transition-colors">
                        {source.title}
                      </div>
                      <div className="text-[10px] text-slate-400 font-mono truncate mt-0.5">
                        {new URL(source.uri).hostname}
                      </div>
                    </div>
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReportView;
    